-- Flyway migration: V1__create_schema_modular_initial.sql
-- Author: jessica_sousa
-- Description: Create initial schema for AUTH_PROFESSIONALS, PATIENT_PATIENTS, and RECORD_RECORDS tables

-- Módulo Auth
CREATE TABLE AUTH_PROFESSIONALS
(
    ID         VARCHAR(36) PRIMARY KEY NOT NULL,
    NAME       VARCHAR(100),
    EMAIL      VARCHAR(100)            NOT NULL UNIQUE,
    PASSWORD   VARCHAR(255),
    ROLE       VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Módulo Patient
CREATE TABLE PATIENT_PATIENTS
(
    ID              VARCHAR(36) PRIMARY KEY NOT NULL,
    FIRST_NAME      VARCHAR(50),
    LAST_NAME       VARCHAR(50),
    CPF             VARCHAR(11)             NOT NULL UNIQUE,
    BIRTH_DATE      DATE,
    PROFESSIONAL_ID VARCHAR(36),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Módulo Record
CREATE TABLE RECORD_RECORDS
(
    ID          VARCHAR(36) PRIMARY KEY NOT NULL,
    PATIENT_ID  VARCHAR(36),
    RECORD_TYPE VARCHAR(30),
    DESCRIPTION TEXT,
    RECORD_DATE TIMESTAMP,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices
CREATE INDEX IDX_PATIENT_PROFESSIONAL_ID ON PATIENT_PATIENTS (PROFESSIONAL_ID);
CREATE INDEX IDX_RECORD_PATIENT_ID ON RECORD_RECORDS (PATIENT_ID);