-- src/main/resources/db/migration/V1__create_schema_modular_initial.sql
-- Author: jessica_sousa
-- Description: Create initial schema for USERS, PATIENT_PATIENTS, and RECORD_RECORDS tables

-- Módulo Auth
CREATE TABLE USER_USERS
(
    ID                      VARCHAR(36) PRIMARY KEY NOT NULL,
    USERNAME                VARCHAR(50)             NOT NULL UNIQUE,
    EMAIL                   VARCHAR(100)            NOT NULL UNIQUE,
    PASSWORD                VARCHAR(255)            NOT NULL,
    ROLE                    VARCHAR(50)             NOT NULL,
    CREATED_AT              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ENABLED                 BOOLEAN   DEFAULT TRUE,
    ACCOUNT_NON_EXPIRED     BOOLEAN   DEFAULT TRUE,
    ACCOUNT_NON_LOCKED      BOOLEAN   DEFAULT TRUE,
    CREDENTIALS_NON_EXPIRED BOOLEAN   DEFAULT TRUE
);

-- Módulo Patient
CREATE TABLE PATIENT_PATIENTS
(
    ID              VARCHAR(36) PRIMARY KEY NOT NULL,
    FIRST_NAME      VARCHAR(50)             NOT NULL,
    LAST_NAME       VARCHAR(50)             NOT NULL,
    CPF             VARCHAR(11)             NOT NULL UNIQUE,
    BIRTH_DATE      DATE                    NOT NULL,
    PROFESSIONAL_ID VARCHAR(36)             NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Módulo Record
CREATE TABLE RECORD_RECORDS
(
    ID          VARCHAR(36) PRIMARY KEY NOT NULL,
    PATIENT_ID  VARCHAR(36)             NOT NULL,
    RECORD_TYPE VARCHAR(30)             NOT NULL,
    DESCRIPTION TEXT                    NOT NULL,
    RECORD_DATE TIMESTAMP               NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices para performance
CREATE INDEX IDX_USER_USERNAME ON USER_USERS (USERNAME);
CREATE INDEX IDX_USER_EMAIL ON USER_USERS (EMAIL);
CREATE INDEX IDX_PATIENT_CPF ON PATIENT_PATIENTS (CPF);
CREATE INDEX IDX_PATIENT_PROFESSIONAL_ID ON PATIENT_PATIENTS (PROFESSIONAL_ID);
CREATE INDEX IDX_RECORD_PATIENT_ID ON RECORD_RECORDS (PATIENT_ID);
CREATE INDEX IDX_RECORD_DATE ON RECORD_RECORDS (RECORD_DATE);